{
 "title": "Original Train Data",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Panel TitleP1_FT01\tx1003_24_SUM_OUT histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT \n    timestamp ,\n   P1_FT01\tx1003_24_SUM_OUT \nFROM train",
     "rawQueryText": "SELECT \n    timestamp ,\n   P1_FT01\tx1003_24_SUM_OUT \nFROM train",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "P1_FCV03D histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "queryText": "SELECT \n    timestamp ,\n   P1_FCV03D \nFROM train",
     "rawQueryText": "SELECT \n    timestamp ,\n   P1_FCV03D \nFROM train",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "x1003_24_SUM_OUT histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "queryText": "SELECT \n    timestamp ,\n    x1003_24_SUM_OUT \nFROM train\n\n",
     "rawQueryText": "SELECT \n    timestamp ,\n    x1003_24_SUM_OUT \nFROM train\n\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Original Data (Train Table)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "queryText": "SELECT timestamp AS time, x1003_24_SUM_OUT AS value\nFROM train\nORDER BY timestamp;\n",
     "rawQueryText": "SELECT timestamp AS time, x1003_24_SUM_OUT AS value\nFROM train\nORDER BY timestamp;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}